// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrivaWebPage.Data.Connection;

#nullable disable

namespace TrivaWebPage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.ActionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActionDefinitions");
                });

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.CardButton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardComponentId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextColor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionDefinitionId");

                    b.HasIndex("CardComponentId");

                    b.ToTable("CardButtons");
                });

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.CardDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreviewMediaFileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreviewMediaFileId");

                    b.ToTable("CardDefinitions");
                });

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.CardFieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CardDefinitionId");

                    b.ToTable("CardFieldDefinitions");
                });

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.CardFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardComponentId")
                        .HasColumnType("int");

                    b.Property<int>("CardFieldDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("FieldValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardComponentId");

                    b.HasIndex("CardFieldDefinitionId");

                    b.ToTable("CardFieldValues");
                });

            modelBuilder.Entity("TrivaWebPage.Models.Contents.ButtonComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageComponentId")
                        .HasColumnType("int");

                    b.Property<string>("SizeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextColor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionDefinitionId");

                    b.HasIndex("PageComponentId")
                        .IsUnique();

                    b.ToTable("ButtonComponents");
                });

            modelBuilder.Entity("TrivaWebPage.Models.Contents.CardComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MediaFileId")
                        .HasColumnType("int");

                    b.Property<int>("PageComponentId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowButton")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowImage")
                        .HasColumnType("bit");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardDefinitionId");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("PageComponentId")
                        .IsUnique();

                    b.ToTable("CardComponents");
                });

            modelBuilder.Entity("TrivaWebPage.Models.Contents.ImageComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BorderRadius")
                        .HasColumnType("int");

                    b.Property<string>("FitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasShadow")
                        .HasColumnType("bit");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("int");

                    b.Property<int>("PageComponentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("PageComponentId")
                        .IsUnique();

                    b.ToTable("ImageComponents");
                });

            modelBuilder.Entity("TrivaWebPage.Models.Contents.TextComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("FontWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsItalic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnderline")
                        .HasColumnType("bit");

                    b.Property<int>("PageComponentId")
                        .HasColumnType("int");

                    b.Property<string>("TextAlign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextColor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PageComponentId")
                        .IsUnique();

                    b.ToTable("TextComponents");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHomePage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.PageMediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MediaFileId")
                        .HasColumnType("int");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("PageId", "MediaFileId")
                        .IsUnique();

                    b.ToTable("PageMediaFiles");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.PageComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CssClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("InlineStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageSectionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PageSectionId");

                    b.ToTable("PageComponents");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.PageSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CssClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("InlineStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("PageSections");
                });

            modelBuilder.Entity("TrivaWebPage.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TrivaWebPage.Models.WebsiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("bit");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebsiteSettings");
                });

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.CardButton", b =>
                {
                    b.HasOne("TrivaWebPage.Models.CardOptions.ActionDefinition", "ActionDefinition")
                        .WithMany("CardButtons")
                        .HasForeignKey("ActionDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrivaWebPage.Models.Contents.CardComponent", "CardComponent")
                        .WithMany("Buttons")
                        .HasForeignKey("CardComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionDefinition");

                    b.Navigation("CardComponent");
                });

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.CardDefinition", b =>
                {
                    b.HasOne("TrivaWebPage.Models.General.MediaFile", "PreviewMediaFile")
                        .WithMany("CardDefinitions")
                        .HasForeignKey("PreviewMediaFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PreviewMediaFile");
                });

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.CardFieldDefinition", b =>
                {
                    b.HasOne("TrivaWebPage.Models.CardOptions.CardDefinition", "CardDefinition")
                        .WithMany("FieldDefinitions")
                        .HasForeignKey("CardDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardDefinition");
                });

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.CardFieldValue", b =>
                {
                    b.HasOne("TrivaWebPage.Models.Contents.CardComponent", "CardComponent")
                        .WithMany("FieldValues")
                        .HasForeignKey("CardComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrivaWebPage.Models.CardOptions.CardFieldDefinition", "CardFieldDefinition")
                        .WithMany()
                        .HasForeignKey("CardFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CardComponent");

                    b.Navigation("CardFieldDefinition");
                });

            modelBuilder.Entity("TrivaWebPage.Models.Contents.ButtonComponent", b =>
                {
                    b.HasOne("TrivaWebPage.Models.CardOptions.ActionDefinition", "ActionDefinition")
                        .WithMany("ButtonComponents")
                        .HasForeignKey("ActionDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrivaWebPage.Models.General.PageComponent", "PageComponent")
                        .WithOne("ButtonComponent")
                        .HasForeignKey("TrivaWebPage.Models.Contents.ButtonComponent", "PageComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionDefinition");

                    b.Navigation("PageComponent");
                });

            modelBuilder.Entity("TrivaWebPage.Models.Contents.CardComponent", b =>
                {
                    b.HasOne("TrivaWebPage.Models.CardOptions.CardDefinition", "CardDefinition")
                        .WithMany("CardComponents")
                        .HasForeignKey("CardDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrivaWebPage.Models.General.MediaFile", "MediaFile")
                        .WithMany("CardComponents")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrivaWebPage.Models.General.PageComponent", "PageComponent")
                        .WithOne("CardComponent")
                        .HasForeignKey("TrivaWebPage.Models.Contents.CardComponent", "PageComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardDefinition");

                    b.Navigation("MediaFile");

                    b.Navigation("PageComponent");
                });

            modelBuilder.Entity("TrivaWebPage.Models.Contents.ImageComponent", b =>
                {
                    b.HasOne("TrivaWebPage.Models.General.MediaFile", "MediaFile")
                        .WithMany("ImageComponents")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrivaWebPage.Models.General.PageComponent", "PageComponent")
                        .WithOne("ImageComponent")
                        .HasForeignKey("TrivaWebPage.Models.Contents.ImageComponent", "PageComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("PageComponent");
                });

            modelBuilder.Entity("TrivaWebPage.Models.Contents.TextComponent", b =>
                {
                    b.HasOne("TrivaWebPage.Models.General.PageComponent", "PageComponent")
                        .WithOne("TextComponent")
                        .HasForeignKey("TrivaWebPage.Models.Contents.TextComponent", "PageComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageComponent");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.PageComponent", b =>
                {
                    b.HasOne("TrivaWebPage.Models.General.PageSection", "PageSection")
                        .WithMany("Components")
                        .HasForeignKey("PageSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageSection");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.PageSection", b =>
                {
                    b.HasOne("TrivaWebPage.Models.General.Page", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.PageMediaFile", b =>
                {
                    b.HasOne("TrivaWebPage.Models.General.MediaFile", "MediaFile")
                        .WithMany("PageMediaFiles")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrivaWebPage.Models.General.Page", "Page")
                        .WithMany("PageMediaFiles")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.ActionDefinition", b =>
                {
                    b.Navigation("ButtonComponents");

                    b.Navigation("CardButtons");
                });

            modelBuilder.Entity("TrivaWebPage.Models.CardOptions.CardDefinition", b =>
                {
                    b.Navigation("CardComponents");

                    b.Navigation("FieldDefinitions");
                });

            modelBuilder.Entity("TrivaWebPage.Models.Contents.CardComponent", b =>
                {
                    b.Navigation("Buttons");

                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.MediaFile", b =>
                {
                    b.Navigation("CardComponents");

                    b.Navigation("CardDefinitions");

                    b.Navigation("ImageComponents");

                    b.Navigation("PageMediaFiles");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.Page", b =>
                {
                    b.Navigation("PageMediaFiles");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.PageComponent", b =>
                {
                    b.Navigation("ButtonComponent");

                    b.Navigation("CardComponent");

                    b.Navigation("ImageComponent");

                    b.Navigation("TextComponent");
                });

            modelBuilder.Entity("TrivaWebPage.Models.General.PageSection", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
